import type { ClientCategory, Permission } from '../entities';

export const DEFAULT_CLIENT_PERMISSIONS = {
  'legal-entity': [
    'dashboard:view',
    'profile:view',
    'profile:update',
    'routing-companies:view',
    'routing-contracts:view',
    'passengers:view',
    'passengers:create',
    'passengers:update',
    'passengers:import',
    'routes:view',
    'contracts:view',
    'quotes:view',
    'quotes:create',
    'trips:view',
    'documents:view',
    'invoices:view',
    'service-requests:view',
    'service-requests:create',
    'support:view',
    'support:create',
  ],
  individual: [
    'dashboard:view',
    'profile:view',
    'profile:update',
    'contracts:view',
    'quotes:view',
    'quotes:create',
    'trips:view',
    'documents:view',
    'invoices:view',
    'service-requests:view',
    'service-requests:create',
    'support:view',
    'support:create',
  ],
  'continuous-charter': [
    'dashboard:view',
    'profile:view',
    'profile:update',
    'contracts:view',
    'quotes:view',
    'quotes:create',
    'trips:view',
    'documents:view',
    'invoices:view',
    'service-requests:view',
    'service-requests:create',
    'support:view',
    'support:create',
  ],

  'eventual-charter': [
    'dashboard:view',
    'profile:view',
    'profile:update',
    'contracts:view',
    'quotes:view',
    'quotes:create',
    'quotes:update',
    'trips:view',
    'documents:view',
    'invoices:view',
    'service-requests:view',
    'service-requests:create',
    'support:view',
    'support:create',
  ],
} as const satisfies Record<ClientCategory, readonly Permission[]>;
