import type { Department, Permission } from '../entities';

export const EMPLOYEE_SELF_SERVICE_PERMISSIONS = [
  'profile:view',
  'profile:update',
  'support:view',
  'support:create',
] as const satisfies readonly Permission[];

export const DEFAULT_DEPARTMENT_PERMISSIONS = {
  'human-resources': [
    'dashboard:view',
    'human-resources:view',
    'human-resources:create',
    'human-resources:update',
    'human-resources:manage',
    'users:view',
    'manuals:view',
    'ai-agents:use',
    'reports:view',
  ],

  'personnel-department': [
    'dashboard:view',
    'personnel-department:view',
    'personnel-department:create',
    'personnel-department:update',
    'personnel-department:manage',
    'users:view',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],

  commercial: [
    'dashboard:view',
    'commercial:view',
    'commercial:create',
    'commercial:update',
    'commercial:manage',
    'clients:view',
    'clients:create',
    'clients:update',
    'whatsapp-conversations:manage',
    'ai-agents:use',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],

  purchasing: [
    'dashboard:view',
    'purchasing:view',
    'purchasing:create',
    'purchasing:update',
    'purchasing:manage',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],

  controlling: [
    'dashboard:view',
    'financial:view',
    'financial:create',
    'financial:update',
    'financial:manage',
    'financial:approve',
    'financial:export',
    'commercial:view',
    'clients:view',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],

  controllership: [
    'dashboard:view',
    'financial:view',
    'financial:create',
    'financial:update',
    'financial:manage',
    'financial:approve',
    'financial:export',
    'commercial:view',
    'clients:view',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],

  maintenance: [
    'dashboard:view',
    'maintenance:view',
    'maintenance:create',
    'maintenance:update',
    'maintenance:manage',
    'operations:view',
    'drivers:view',
    'manuals:view',
    'reports:view',
  ],

  monitoring: [
    'dashboard:view',
    'monitoring:view',
    'monitoring:create',
    'monitoring:update',
    'monitoring:manage',
    'operations:view',
    'drivers:view',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],

  management: [
    'dashboard:view',
    'operations:view',
    'operations:create',
    'operations:update',
    'operations:manage',
    'monitoring:view',
    'maintenance:view',
    'commercial:view',
    'financial:view',
    'clients:view',
    'drivers:view',
    'drivers:manage',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],

  operations: [
    'dashboard:view',
    'operations:view',
    'operations:create',
    'operations:update',
    'operations:manage',
    'monitoring:view',
    'maintenance:view',
    'cleaning:view',
    'drivers:view',
    'drivers:manage',
    'ai-agents:use',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],

  cleaning: [
    'dashboard:view',
    'cleaning:view',
    'cleaning:update',
    'operations:view',
    'manuals:view',
  ],

  financial: [
    'dashboard:view',
    'financial:view',
    'financial:create',
    'financial:update',
    'financial:manage',
    'financial:approve',
    'financial:export',
    'commercial:view',
    'clients:view',
    'manuals:view',
    'reports:view',
    'reports:export',
  ],

  'information-technology': [
    'dashboard:view',
    'users:view',
    'users:create',
    'users:update',
    'users:delete',
    'users:manage',
    'ai-agents:view',
    'ai-agents:create',
    'ai-agents:update',
    'ai-agents:delete',
    'ai-agents:manage',
    'ai-agents:use',
    'manuals:view',
    'manuals:create',
    'manuals:update',
    'manuals:delete',
    'manuals:manage',
    'reports:view',
    'reports:export',
    'settings:view',
    'settings:update',
    'settings:manage',
  ],
} as const satisfies Record<Department, readonly Permission[]>;
