const MILLISECONDS_PER_SECOND = 1_000;
const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const HOURS_PER_DAY = 24;

export const DEFAULT_SESSION_DURATION_HOURS = 8 as const;

export const REMEMBERED_SESSION_DURATION_DAYS = 30 as const;

export const DEFAULT_SESSION_DURATION_MS =
  DEFAULT_SESSION_DURATION_HOURS * MINUTES_PER_HOUR * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;

export const REMEMBERED_SESSION_DURATION_MS =
  REMEMBERED_SESSION_DURATION_DAYS *
  HOURS_PER_DAY *
  MINUTES_PER_HOUR *
  SECONDS_PER_MINUTE *
  MILLISECONDS_PER_SECOND;
